### ISSUE TITLE
Hide webpack and karma CLIs and config

### ISSUE THREAD

**Issue by pirelenito** [saguijs/sagui#117]
The `v5` beta release has been trying a novel approach on Sagui of exposing the internals of Webpack and Karma to the end user. After some user research, some issues were raised with this approach:

- The first and most important is that on `package.json` we see references to (for example) `webpack-dev-server` but that is no where defined as a dependency, which might bring confusion;
- There is always the issue of Sagui's internal configuration conflict with a user webpack configuration in upcoming releases, effectively making the entire webpack configuration API surface.

Given these considerations, a middle-ground must be established.

- Sagui should enforce a good set of defaults that is going to be enough for most people;
- It should also allow configuration the most common patterns in the community through its own configuration format (not webpack's);
- As a last solution, advanced users might extend the internal Sagui configuration, in which case Sagui must warn the user of possible conflicts.

The idea then, is to have a single `sagui.config.js` file again such as:

```js
var sagui = require('sagui')

module.exports = sagui({
  publicPath: 'https://my-private-cdn.net/app/',
  pages: ['index', 'fullscreen'],
  buildDependencies: ['ui-react-components']
})
```

That will in most cases be actually:

```js
var sagui = require('sagui')

module.exports = sagui({})
```

And in some, might be:

```js
var sagui = require('sagui')

module.exports = sagui({
  publicPath: 'https://my-private-cdn.net/app/',
  pages: ['index', 'fullscreen'],
  buildDependencies: ['ui-react-components'],
  disabledFeatures: ['style'],
  webpack: {
    plugins: [new GitRevisionPlugin()]
  },
  karma: {
    browsers: ['Chrome']
  }
})
```

Since we are going back to have our own CLI, we should think on adding more powerful features based on Karma's and Webpack's.

This issue would make the current v5 obsolete, jumping the stable version of Sagui directly from v4 to v6.

**Comment by xaviervia** [comment]
I'm not sure about this change. I actually can see many benefits in being transparent about the internal tools, since sagui is not meant to replace them. As a direct consequence of hiding them, googling for issues will be harder. But it doesn't end there: by making it more difficult to add standard webpack and karma configurations, sagui is less useful as a boilerplate, and risks putting users in the position of having to migrate from sagui to vanilla webpack/karma once a mature project evolves beyond the reach of sagui. 

I think a good reason for taking this approach would be if sagui were to, at some point, let go of webpack for rollup or something like that, but my understanding of sagui meant that that was unlikely and not something that was planned for.

**Comment by pirelenito** [comment]
Here is a target for how the configuration object should be:

```js
const config = {
  hotReloading: false,
  optimize: false,
  defineNodeEnv: false,
  clean: false,
  testCoverage: false,
  lint: false,

  pages: ['examples/index'],
  library: 'ReactEntanglement',

  disabledLoaders: ['javaScript', 'images'],

  javaScript: {
    buildDependencies: ['ui-react-components']
  },

  webpack: {
    plugins: [new GitRevisionPlugin()]
  },

  karma: {
    browsers: ['Chrome']
  }
}
```

The minimum you need to get an app is:

```js
const config = {
  pages: ['examples/index']
}
```

**Comment by pirelenito** [comment]
Closing this issue, as most of the remaining work was split into other issues.
