### ISSUE TITLE
Best way to integrate Basscss

### ISSUE THREAD

**Issue by twe4ked** [saguijs/sagui#169]
I'm wondering what the best way to integrate [Basecss](http://www.basscss.com/) is.

I installed the npm package and imported it into the Javascript:

```
import basecss from 'basscss/css/basscss.css'
```

But this gets complicated quickly when I try to include some of the [addons](https://github.com/basscss/addons/tree/master/modules/btn-outline).

```
import basecssBtn from …
```

Is there a nicer way to do this? Would it be better/possible to include all the styles in the actual page and reference them by their “normal” class names?

Thanks!

**Comment by xaviervia** [comment]
Hi! Thanks for reaching out. 

I have no experience with Basscss in particular, but it seems to be a CSS library akin to Twitter's Bootstrap, that is, one that provides a set of global CSS classes. If that's the case, what I can say is that CSS modules are not the best fit for the project. You can [disable CSS Modules](https://github.com/saguijs/sagui#stylecssmodules) in your `sagui.config.js` file so that the Basscss classes don't get hashed.

About how to include the actual CSS files in the document, using `<link>` tags directly on the HTML template won't work, because webpack won't pick them up and build them. Instead, you can use the `@import` clause in the `index.css` file:

```css
@import 'basscss.css';

.component {

}
```

I believe there might be a way to add them to the `index.html` so that webpack's `html-loader` picks them up correctly, but I'm not sure on how. Meanwhile the `@import` works. The path to the `basscss.css` file might be a little convoluted though: I haven't tried it with an npm dependency, but it might involve something like `../node_modules/basscss/basscss.css`.

Hope this helps.

**Comment by pirelenito** [comment]
Hi @twe4ked,

As @xaviervia stated, the problem you are having (if I understood it correctly) is that your class names are being "scoped locally" by our [CSS Modules](https://github.com/css-modules/css-modules) implementation.

If you want to have the classes in the "global" scope you can disable CSS Modules in Sagui very easily. In the `sagui.config.js`:

```js
module.exports = {
  style: {
    cssModules: false
  }
}
```

Let us know if this helps!

**Comment by twe4ked** [comment]
That worked perfectly! Thanks very much :)

For reference:

```
@import '../node_modules/basscss/css/basscss.css';
@import '../node_modules/basscss-addons/modules/btn/index.css';
@import '../node_modules/basscss-addons/modules/btn-outline/index.css';
```
