### ISSUE TITLE
Using airbnb style guide

### ISSUE THREAD

**Issue by kazzkiq** [saguijs/sagui#191]
I've tried to update my Sagui sample project to use airbnb styleguide, but couldn't get it to work. Here is what I tried:

 1) **Change `.eslintrc` to:**

``` json
{
  "extends": "airbnb"
}
```

 2) **Run the command:** `npm install --save-dev eslint-config-airbnb`

But once I run the npm command I get this error on terminal:

``` bash
sagui-project@1.0.0 /sagui-project
├── UNMET PEER DEPENDENCY eslint@^2.10.2 || 3.x
├── UNMET PEER DEPENDENCY eslint-plugin-import@^1.7.0
├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@2.0.1 extraneous
└── UNMET PEER DEPENDENCY eslint-plugin-react@^5.0.1
```

Is there any proper way to do it?

**Comment by pirelenito** [comment]
Hi @kazzkiq! Thanks for reporting the issue :)

The problem happens because the dependencies you require for the airbnb config is conflicting with the peerDependencies required to setup our own linting configuration.

This gives you a couple of options:

- Embrace [Standard](http://standardjs.com/) as your new linting configuration (it shouldn't matter much if you think about the other benefits you are getting of this tool);
- Try to find a version of the `eslint-config-airbnb` that works with the plugins we already provide;
- Change your project's `.eslincrc` to tweak the Sagui configuration so that it suits your needs better.

I will investigate if we can update our internal eslint dependencies so that it is compatible with the airbnb configuration but as of right now the plan is to keep Sagui simple and I wouldn't be able to guarantee future support.

The `.saguirc` file is bootstrapped to allow a certain level of customization and most importantly decent integration with IDEs and text editors.

I'll leave the issue open as I investigate the dependencies better.

**Comment by kazzkiq** [comment]
Thanks for the reply.

For now I will keep using Standard, but I think it would be very interesting if Sagui also managed to let open for users to choose which style guide they want to use (sometimes its hard to change style guides just for a single project on a company that already use another one).

Awesome project, btw. 👍

**Comment by pirelenito** [comment]
This will become viable once https://github.com/eslint/eslint/issues/3458#issuecomment-241326231 is resolved.

**Comment by karthikiyengar** [comment]
@pirelenito - I understand that there's we are waiting on the eslint issue, but is it possible to bump our plugins to allow simpler integration of the styleguide? Any other workarounds?

**Comment by pirelenito** [comment]
Allowing custom ESLint configurations makes the internals of Sagui a lot more complicated and can create weird issues for users.

Therefore in the upcoming [v9](https://github.com/saguijs/sagui/tree/v9) release, we are dropping support for custom ESLint configurations and sticking to StandardJS.

We will be coming with a migration instruction once the final release is out.

You can try it out today with `npm install --save-dev sagui@beta`

Thanks again for using Sagui! ❤️
